inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'samples/**/*'
    - 'lib/llvm/config.rb'

# Style
Style/ClassAndModuleChildren:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

# Layout
Layout/EndAlignment:
  AutoCorrect: true
  EnforcedStyleAlignWith: variable

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/AlignHash:
  Enabled: false

# Exceptions
Style:
  Exclude:
    - 'lib/**/*ffi.rb'

Layout/IndentationWidth:
  Exclude:
    - 'lib/**/*ffi.rb'
