inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'samples/**/*'
    - 'lib/llvm/config.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EndAlignment:
  AutoCorrect: true
  EnforcedStyleAlignWith: variable

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Style:
  Exclude:
    - 'lib/**/*ffi.rb'

Layout/IndentationWidth:
  Exclude:
    - 'lib/**/*ffi.rb'
